- name: Install package from a remote repo
  hosts: web1
  become: yes
  tasks:
  -  name: Install package from remote repo
     yum:
       name: http://mirror.centos.org/centos/7/os/x86_64/Packages/wget-1.14-18.el7_6.1.x86_64.rpm
       state: present